In [1]:
import numpy as np

In [2]:
simple_list = [4,8,12]
np.array(simple_list)

array([ 4,  8, 12])

In [3]:
arr = np.array([1,4,6])
arr

array([1, 4, 6])

In [5]:
list_of_lists=([1,2,3],[4,5,8],[6,0,10])
np.array(list_of_lists)

array([[ 1,  2,  3],
       [ 4,  5,  8],
       [ 6,  0, 10]])

In [6]:
np.arange(7,27)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26])

In [7]:
np.arange(5,23,9)

array([ 5, 14])

In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [10]:
np.ones(8,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [11]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.linspace(0,27,12)

array([ 0.        ,  2.45454545,  4.90909091,  7.36363636,  9.81818182,
       12.27272727, 14.72727273, 17.18181818, 19.63636364, 22.09090909,
       24.54545455, 27.        ])

In [18]:
np.eye(7,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [16]:
np.random.rand(3,7)

array([[0.66047789, 0.11978116, 0.53920422, 0.29710691, 0.54653269,
        0.60520739, 0.26445796],
       [0.74270849, 0.75251711, 0.32260389, 0.15418134, 0.73454684,
        0.8037425 , 0.14593903],
       [0.79966416, 0.52184148, 0.47988931, 0.8815137 , 0.82100578,
        0.48547743, 0.66207582]])

In [17]:
np.random.randn(3,7)

array([[-1.35420802,  1.3377705 ,  0.32466793,  1.1778025 , -0.81762748,
        -1.79535085, -0.50699156],
       [ 0.49820507,  0.11797368,  2.87864126, -1.41907211,  1.12270836,
         0.35455857,  0.60332441],
       [-0.21557631, -0.6261856 , -0.57742466,  0.52494417,  0.65690212,
        -0.87906648,  1.40243282]])

In [19]:
np.random.randint(0,12,20)

array([ 7,  2,  1,  5,  7,  6,  9,  5,  5,  6,  7,  5, 11,  6,  6,  3, 10,
        0, 11,  1])

In [20]:
np.random.randint(10,30,50)

array([28, 28, 26, 21, 26, 17, 23, 13, 29, 18, 28, 17, 13, 11, 17, 28, 19,
       14, 18, 12, 12, 29, 26, 17, 13, 17, 23, 22, 15, 22, 12, 24, 25, 21,
       13, 13, 19, 21, 18, 27, 20, 22, 14, 24, 15, 29, 25, 27, 23, 21])

In [22]:
import numpy as np

In [25]:
sample_array = np.arange(2,21)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [27]:
rand_array = np.random.randint(0,21,5)
rand_array

array([18, 12, 14,  0,  6])

In [28]:
sample_array.argmin()

0

In [29]:
rand_array.argmin()

3

In [30]:
rand_array.max()

18

In [31]:
rand_array.argmax()

0

In [32]:
sample_array.argmax()

18

In [33]:
sample_array.dtype

dtype('int32')

In [35]:
a = np.eye(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [36]:
a.T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [37]:
a = np.random.rand(2,3)
a

array([[0.29798622, 0.42385008, 0.77953058],
       [0.73279244, 0.65357419, 0.27061951]])

In [38]:
a.T


array([[0.29798622, 0.73279244],
       [0.42385008, 0.65357419],
       [0.77953058, 0.27061951]])

In [39]:
import numpy as np


In [40]:
sample_array = np.arange(10,112)
sample_array

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])

In [41]:
sample_array[1:11]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
subset_sample_array = sample_array[0:6]
subset_sample_array

array([10, 11, 12, 13, 14, 15])

In [43]:
sample_array[:]= 1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001])

In [44]:
import numpy as np

In [47]:
sample_matrix=np.array(([24,12,13,20],[15,16,97,20],[42,23,18,20]))
sample_matrix

array([[24, 12, 13, 20],
       [15, 16, 97, 20],
       [42, 23, 18, 20]])

In [2]:
import numpy as np

In [3]:
sample_array = np.arange(10,23)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [5]:
sample_array = sample_array.reshape(2,6)
sample_array

ValueError: cannot reshape array of size 13 into shape (2,6)

In [6]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [7]:
sample_array[:]=1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001])